### ISSUE TITLE
Can not switch context in Android 6.0 container

### ISSUE THREAD

**Issue by sasha943** [aerokube/images#171]
Use last selenoid-images scripts

Build custom Android image:
Appium version: 1.9.1
device name: Nexus 9
Android version: 6.0
chromedriver version: 2.20
Testing native app

When try change context from native to webview have an exception:
`Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'alex-System-Product-Name', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-54-generic', java.version: '11.0.4-ea'
Driver info: driver.version: ApplicationDriver
Capabilities {androidInstallTimeout: 200000, androidNaturalOrientation: true, app: /etc/release/app-universal-..., appActivity: com.*.app.activity.m..., appPackage: com.*.mobile.test, appWaitActivity: com.*.app.activity.m..., appWaitDuration: 120000, appWaitPackage: com.*.mobile.test, autoGrantPermissions: true, automationName: Appium, browserName: android, clearSystemFiles: true, databaseEnabled: false, desired: {androidInstallTimeout: 200000, androidNaturalOrientation: true, app: /etc/release/app-universal-..., appActivity: com.*.app.activity.m..., appWaitDuration: 120000, autoGrantPermissions: true, automationName: Appium, browserName: android, clearSystemFiles: true, deviceName: emulator-5554, disableAndroidWatchers: true, enableLog: true, enableVNC: true, enableVideo: false, javascriptEnabled: true, name: androidContainerWithName_15..., nativeWebScreenshot: true, newCommandTimeout: 3600, noReset: true, noSign: true, orientation: LANDSCAPE, platformName: Android, recreateChromeDriverSessions: true, resetKeyboard: true, setWebContentsDebuggingEnabled: true, takesScreenshot: true, udid: emulator-5554, unicodeKeyboard: true, version: 8.0}, deviceManufacturer: unknown, deviceModel: Android SDK built for x86, deviceName: emulator-5554, deviceScreenSize: 1536x2048, deviceUDID: emulator-5554, disableAndroidWatchers: true, enableLog: true, enableVNC: true, enableVideo: false, javascriptEnabled: true, locationContextEnabled: false, name: androidContainerWithName_15..., nativeWebScreenshot: true, networkConnectionEnabled: true, newCommandTimeout: 3600, noReset: true, noSign: true, orientation: LANDSCAPE, platform: LINUX, platformName: Android, platformVersion: 6.0, recreateChromeDriverSessions: true, resetKeyboard: true, setWebContentsDebuggingEnabled: true, takesScreenshot: true, udid: emulator-5554, unicodeKeyboard: true, version: 8.0, warnings: {}, webStorageEnabled: false}
Session ID: 6efd1b0a-e5b2-4474-a1ef-fad698087818
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at io.appium.java_client.AppiumDriver.context(AppiumDriver.java:198)
	... 29 more
Caused by: java.lang.IllegalArgumentException: Cannot decode response content: 
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:83)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	... 33 more
Caused by: org.openqa.selenium.json.JsonException: Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'alex-System-Product-Name', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-54-generic', java.version: '11.0.4-ea'
Driver info: driver.version: ApplicationDriver
	at org.openqa.selenium.json.JsonInput.expect(JsonInput.java:289)
	at org.openqa.selenium.json.JsonInput.beginObject(JsonInput.java:219)
	at org.openqa.selenium.json.MapCoercer.lambda$apply$1(MapCoercer.java:64)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:142)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:123)
	at org.openqa.selenium.json.ResponseCoercer.lambda$apply$0(ResponseCoercer.java:50)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:142)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:123)
	at org.openqa.selenium.json.Json.toType(Json.java:60)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	... 37 more`

Container present and I can click with VNC.

On Android 8.1 (chromedriver 2.40) change context works.

**Comment by vania-pooh** [comment]
@sasha943 any Appium logs inside container?

**Comment by sasha943** [comment]
`2019-07-08 07:10:03:545 - [debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["0acb1469-1789-492e-9ff4-21e61842e618"]
2019-07-08 07:10:03:546 - [debug] [AndroidDriver] Getting a list of available webviews
2019-07-08 07:10:03:546 - [debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s emulator-5554 shell cat /proc/net/unix'
2019-07-08 07:10:03:559 - [debug] [AndroidDriver] WEBVIEW_2913 mapped to pid 2913
2019-07-08 07:10:03:560 - [debug] [AndroidDriver] Getting process name for webview
2019-07-08 07:10:03:560 - [debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s emulator-5554 shell ps'
2019-07-08 07:10:03:590 - [debug] [AndroidDriver] Parsed pid: '2913' pkg: 'com.*.mobile.test' from
2019-07-08 07:10:03:592 - [debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN            PC  NAME
2019-07-08 07:10:03:592 - [debug] [AndroidDriver]     u0_a58    2913  1264  1241240 136656 SyS_epoll_ b72fafa5 S com.*.mobile.test
2019-07-08 07:10:03:592 - [debug] [AndroidDriver] Returning process name: 'com.*.mobile.test'
2019-07-08 07:10:03:592 - [debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.*.mobile.test"]
2019-07-08 07:10:03:592 - [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.*.mobile.test"]
2019-07-08 07:10:03:593 - [debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com.*.mobile.test"]
2019-07-08 07:10:03:595 - [HTTP] <-- GET /wd/hub/session/0acb1469-1789-492e-9ff4-21e61842e618/contexts 200 49 ms - 117
2019-07-08 07:10:03:596 - [HTTP] 
2019-07-08 07:10:03:599 - [HTTP] --> POST /wd/hub/session/0acb1469-1789-492e-9ff4-21e61842e618/context
2019-07-08 07:10:03:599 - [HTTP] {"name":"WEBVIEW_com.*.mobile.test"}
2019-07-08 07:10:03:600 - [debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.*.mobile.test","0acb1469-1789-492e-9ff4-21e61842e618"]
2019-07-08 07:10:03:601 - [debug] [AndroidDriver] Getting a list of available webviews
2019-07-08 07:10:03:601 - [debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s emulator-5554 shell cat /proc/net/unix'
2019-07-08 07:10:03:619 - [debug] [AndroidDriver] WEBVIEW_2913 mapped to pid 2913
2019-07-08 07:10:03:619 - [debug] [AndroidDriver] Getting process name for webview
2019-07-08 07:10:03:619 - [debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s emulator-5554 shell ps'
2019-07-08 07:10:03:644 - [debug] [AndroidDriver] Parsed pid: '2913' pkg: 'com.*.mobile.test' from
2019-07-08 07:10:03:644 - [debug] [AndroidDriver]     USER      PID   PPID  VSIZE  RSS   WCHAN            PC  NAME
2019-07-08 07:10:03:645 - [debug] [AndroidDriver]     u0_a58    2913  1264  1241240 136656 SyS_epoll_ b72fafa5 S com.*.mobile.test
2019-07-08 07:10:03:645 - [debug] [AndroidDriver] Returning process name: 'com.*.mobile.test'
2019-07-08 07:10:03:645 - [debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.*.mobile.test"]
2019-07-08 07:10:03:646 - [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.*.mobile.test"]
2019-07-08 07:10:03:646 - [debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.*.mobile.test'
2019-07-08 07:10:03:652 - [debug] [AndroidDriver] A port was not given, using random port: 8000
2019-07-08 07:10:03:654 - [debug] [Chromedriver] Changed state to 'starting'
2019-07-08 07:10:03:655 - [Chromedriver] Set chromedriver binary as: /usr/bin/chromedriver
2019-07-08 07:10:03:656 - [debug] [Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/usr/bin/chromedriver.*--port=8000"
2019-07-08 07:10:03:668 - [Chromedriver] No old chromedrivers seemed to exist
2019-07-08 07:10:03:668 - [debug] [Chromedriver] Cleaning any old adb forwarded port socket connections
2019-07-08 07:10:03:668 - [debug] [ADB] List forwarding ports
2019-07-08 07:10:03:669 - [debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s emulator-5554 forward --list'
2019-07-08 07:10:03:677 - [Chromedriver] Spawning chromedriver with: /usr/bin/chromedriver --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
2019-07-08 07:10:03:695 - [Chromedriver] Chromedriver exited unexpectedly with code 127, signal null
2019-07-08 07:10:03:696 - [debug] [Chromedriver] Changed state to 'stopped'
2019-07-08 07:10:47:598 - [HTTP] --> DELETE /wd/hub/session/f2c2ffee-05c5-4fdd-8175-d69ab8718edc
2019-07-08 07:10:47:598 - [HTTP] {}
2019-07-08 07:10:47:611 - [debug] [GENERIC] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
2019-07-08 07:10:47:611 - [debug] [GENERIC]     at asyncHandler$ (/opt/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:260:15)
2019-07-08 07:10:47:611 - [debug] [GENERIC]     at tryCatch (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
2019-07-08 07:10:47:613 - [debug] [GENERIC]     at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
2019-07-08 07:10:47:613 - [debug] [GENERIC]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2019-07-08 07:10:47:613 - [debug] [GENERIC]     at invoke (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2019-07-08 07:10:47:613 - [debug] [GENERIC]     at enqueueResult (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
2019-07-08 07:10:47:613 - [debug] [GENERIC]     at new Promise (<anonymous>)
2019-07-08 07:10:47:613 - [debug] [GENERIC]     at new F (/opt/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
2019-07-08 07:10:47:614 - [debug] [GENERIC]     at AsyncIterator.enqueue (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
2019-07-08 07:10:47:614 - [debug] [GENERIC]     at AsyncIterator.prototype.(anonymous function) [as next] (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
2019-07-08 07:10:47:614 - [debug] [GENERIC]     at Object.runtime.async (/opt/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
2019-07-08 07:10:47:614 - [debug] [GENERIC]     at asyncHandler (/opt/node_modules/appium/node_modules/appium-base-driver/build/lib/protocol/protocol.js:380:32)
2019-07-08 07:10:47:614 - [debug] [GENERIC]     at /opt/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:446:15
2019-07-08 07:10:47:614 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2019-07-08 07:10:47:614 - [debug] [GENERIC]     at next (/opt/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
2019-07-08 07:10:47:615 - [debug] [GENERIC]     at Route.dispatch (/opt/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
2019-07-08 07:10:47:615 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2019-07-08 07:10:47:615 - [debug] [GENERIC]     at /opt/node_modules/appium/node_modules/express/lib/router/index.js:281:22
2019-07-08 07:10:47:615 - [debug] [GENERIC]     at param (/opt/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
2019-07-08 07:10:47:615 - [debug] [GENERIC]     at param (/opt/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
2019-07-08 07:10:47:615 - [debug] [GENERIC]     at Function.process_params (/opt/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
2019-07-08 07:10:47:615 - [debug] [GENERIC]     at next (/opt/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2019-07-08 07:10:47:616 - [debug] [GENERIC]     at logger (/opt/node_modules/appium/node_modules/morgan/index.js:144:5)
2019-07-08 07:10:47:616 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2019-07-08 07:10:47:616 - [debug] [GENERIC]     at trim_prefix (/opt/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2019-07-08 07:10:47:616 - [debug] [GENERIC]     at /opt/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2019-07-08 07:10:47:616 - [debug] [GENERIC]     at Function.process_params (/opt/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2019-07-08 07:10:47:616 - [debug] [GENERIC]     at next (/opt/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2019-07-08 07:10:47:616 - [debug] [GENERIC]     at jsonParser (/opt/node_modules/appium/node_modules/body-parser/lib/types/json.js:110:7)
2019-07-08 07:10:47:617 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2019-07-08 07:10:47:617 - [debug] [GENERIC]     at trim_prefix (/opt/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2019-07-08 07:10:47:617 - [debug] [GENERIC]     at /opt/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2019-07-08 07:10:47:619 - [debug] [GENERIC]     at Function.process_params (/opt/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2019-07-08 07:10:47:619 - [debug] [GENERIC]     at next (/opt/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2019-07-08 07:10:47:619 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at trim_prefix (/opt/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at /opt/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at Function.process_params (/opt/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at next (/opt/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:91:12)
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at trim_prefix (/opt/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at /opt/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2019-07-08 07:10:47:620 - [debug] [GENERIC]     at Function.process_params (/opt/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2019-07-08 07:10:47:621 - [debug] [GENERIC]     at next (/opt/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2019-07-08 07:10:47:621 - [debug] [GENERIC]     at methodOverride (/opt/node_modules/appium/node_modules/method-override/index.js:65:14)
2019-07-08 07:10:47:621 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2019-07-08 07:10:47:621 - [debug] [GENERIC]     at trim_prefix (/opt/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
2019-07-08 07:10:47:621 - [debug] [GENERIC]     at /opt/node_modules/appium/node_modules/express/lib/router/index.js:284:7
2019-07-08 07:10:47:621 - [debug] [GENERIC]     at Function.process_params (/opt/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
2019-07-08 07:10:47:621 - [debug] [GENERIC]     at next (/opt/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
2019-07-08 07:10:47:622 - [debug] [GENERIC]     at urlencodedParser (/opt/node_modules/appium/node_modules/body-parser/lib/types/urlencoded.js:91:7)
2019-07-08 07:10:47:622 - [debug] [GENERIC]     at Layer.handle [as handle_request] (/opt/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
2019-07-08 07:10:47:624 - [HTTP] <-- DELETE /wd/hub/session/f2c2ffee-05c5-4fdd-8175-d69ab8718edc 404 25 ms - 5450
2019-07-08 07:10:47:624 - [HTTP] `

**Comment by vania-pooh** [comment]
@sasha943 so far as I can see session does not start.

**Comment by sasha943** [comment]
@vania-pooh is it possible that chromedriver not downloaded during container build? Tried build several time. On android 8.1 (chromedriver 2.40) everything works

**Comment by vania-pooh** [comment]
@sasha943 it is possible. To check - just go inside container and see whether the binary is present.

**Comment by sasha943** [comment]
@vania-pooh as I wrote chromedriver present by path /usr/bin/chromedriver. Also I built image Android 6.0 (chromedriver 2.20) from scrips that was developed in February (or smth like that do not remember) and everything works
